# Generated by Django 4.2.6 on 2023-11-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_name_1', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('date', 'Date'), ('text', 'Text')], max_length=100)),
                ('field_name_2', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('date', 'Date'), ('text', 'Text')], max_length=100)),
            ],
        ),
    ]
