version: '3'

services:
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  data_loader:
    build:
      context: .
      dockerfile: Dockerfile_data_loader 
    depends_on:
      - db